# Generated by Django 5.2.5 on 2025-08-30 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=5, max_digits=20)),
                ('unidad', models.CharField(choices=[('kg', 'Kilogramo'), ('L', 'Litro'), ('UNIDAD', 'Unidad')], default='UNIDAD', max_length=10)),
                ('ultima_vez_actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoTerminado',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=5, max_digits=20)),
                ('codigoMateriaPrima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MateriaPrimaGestor.materiaprima')),
                ('codigoProductoTerminado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MateriaPrimaGestor.productoterminado')),
            ],
            options={
                'unique_together': {('codigoMateriaPrima', 'codigoProductoTerminado')},
            },
        ),
    ]
