# Generated by Django 5.2.5 on 2025-08-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MateriaPrimaGestor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='cantidad',
            field=models.DecimalField(decimal_places=5, default='UNIDAD', max_digits=20),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='unidad',
            field=models.CharField(choices=[('kg', 'Kilogramo'), ('L', 'Litro'), ('UNIDAD', 'Unidad')], default='kg', max_length=10),
        ),
    ]
