# Generated by Django 5.2.5 on 2026-02-27 01:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MateriaPrimaGestor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoterminado',
            name='cantidad',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
