# Generated by Django 5.2.5 on 2025-09-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MateriaPrimaGestor', '0002_alter_materiaprima_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='cantidad',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
    ]
