# Generated by Django 5.2.5 on 2026-03-06 01:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MateriaPrimaGestor', '0002_productoterminado_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccionproducto',
            name='cantidad_unidad',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
