# Generated by Django 5.2.5 on 2026-03-23 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MateriaPrimaGestor', '0003_produccionproducto_cantidad_unidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleproducto',
            options={'ordering': ['codigo']},
        ),
        migrations.AlterModelOptions(
            name='producciondetalle',
            options={'ordering': ['codigo']},
        ),
    ]
