# Generated by Django 5.2.5 on 2025-09-05 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MateriaPrimaGestor', '0003_alter_materiaprima_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producida', models.DecimalField(decimal_places=5, max_digits=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MateriaPrimaGestor.productoterminado')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumoMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usada', models.DecimalField(decimal_places=5, max_digits=20)),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MateriaPrimaGestor.materiaprima')),
                ('produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='MateriaPrimaGestor.produccion')),
            ],
        ),
    ]
