# Generated by Django 5.2.5 on 2026-04-27 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MateriaPrimaGestor', '0004_alter_detalleproducto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleproducto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='producciondetalle',
            options={},
        ),
    ]
