# Generated by Django 5.2.5 on 2026-02-23 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MateriaPrimaGestor', '0004_produccion_consumomateriaprima'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detalleproducto',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='detalleproducto',
            name='codigoMateriaPrima',
        ),
        migrations.RemoveField(
            model_name='detalleproducto',
            name='codigoProductoTerminado',
        ),
        migrations.RemoveField(
            model_name='produccion',
            name='producto',
        ),
        migrations.DeleteModel(
            name='ConsumoMateriaPrima',
        ),
        migrations.DeleteModel(
            name='MateriaPrima',
        ),
        migrations.DeleteModel(
            name='DetalleProducto',
        ),
        migrations.DeleteModel(
            name='Produccion',
        ),
        migrations.DeleteModel(
            name='ProductoTerminado',
        ),
    ]
