# Generated by Django 5.2.5 on 2026-02-23 02:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MateriaPrimaGestor', '0005_alter_detalleproducto_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('unidad', models.CharField(choices=[('KG', 'Kilogramos'), ('L', 'Litros'), ('G', 'Gramos'), ('ML', 'Mililitros'), ('U', 'Unidad')], max_length=5)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('costo', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoTerminado',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProduccionProducto',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MateriaPrimaGestor.productoterminado')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MateriaPrimaGestor.materiaprima')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MateriaPrimaGestor.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='ProduccionDetalle',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MateriaPrimaGestor.materiaprima')),
                ('produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MateriaPrimaGestor.produccionproducto')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('produccion', 'materia_prima'), name='unique_materia_por_produccion')],
            },
        ),
        migrations.CreateModel(
            name='DetalleProducto',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MateriaPrimaGestor.materiaprima')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MateriaPrimaGestor.productoterminado')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('producto', 'materia_prima'), name='unique_materia_por_producto')],
            },
        ),
    ]
