# Generated by Django 5.2.5 on 2026-02-23 02:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MateriaPrimaGestor', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproducto',
            name='cantidad',
            field=models.DecimalField(decimal_places=5, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='cantidad',
            field=models.DecimalField(decimal_places=5, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='producciondetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=5, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='produccionproducto',
            name='cantidad',
            field=models.DecimalField(decimal_places=5, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
