# Generated by Django 5.2.5 on 2026-02-23 02:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MateriaPrimaGestor', '0007_alter_detalleproducto_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
